apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: orderflow
type: Opaque
data:
  POSTGRES_PASSWORD: c2VjcmV0
  JWT_SECRET: NDA0RTYzNTI2NjU1NkE1ODZFMzI3MjM1NzUzODc4MkY0MTNGNDQyODQ3MkI0QjYyNTA2NDUzNjc1NjZCNTk3MA==
  MAIL_PASSWORD: <base64-of-your-gmail-app-password>
  MAIL_USERNAME: <base64-of-your-gmail-address>