apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: orderflow
data:
  POSTGRES_URL: jdbc:postgresql://postgres-service:5432/orderflow
  REDIS_HOST: redis-service
  KAFKA_SERVERS: kafka-service:9092
  MONGODB_URI: mongodb://mongo-service:27017/orderflow_products