apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: orderflow
spec:
  selector:
    app: notification-service
  ports:
    - port: 8084
      targetPort: 8084
  type: ClusterIP